### ISSUE TITLE
Merchant Item Update

### ISSUE THREAD

**Issue by zamiraskaff** [sunny-moore/little-esty-shop#9]
As a merchant,
When I visit the merchant show page of an item
I see a link to update the item information.
When I click the link
Then I am taken to a page to edit this item
And I see a form filled in with the existing item attribute information
When I update the information in the form and I click ‘submit’
Then I am redirected back to the item show page where I see the updated information
And I see a flash message stating that the information has been successfully updated.

**Comment by tig-o** [comment]
This one has been deployed already, but for some reason it is not being routed to the update form. I am looking through the slack channel maybe I missed something regarding this one

**Comment by tig-o** [comment]
@alepbloyd

**Comment by alepbloyd** [comment]
@tig-o 

Weird, thanks for the heads up! I imagine something with doing this before changing to using resources for routing, but I would've expected to see some failing tests. I'll take a look at it tomorrow.

**Comment by tig-o** [comment]
@alepbloyd 

Just tested again and the feature works. The part that doesn't work is the 'update link'. We might just have to update the link to take the user to the specific items edit page. Im guessing either a routes issue or just updating the view page 'update link'.

**Example:**

The following link takes you to the item show page and the update link in this page takes you to the same page it is already on:

https://little-esty-shop-project.herokuapp.com/merchants/1/items/2

However when I manually type the edit URL for this specific item I am taken to the form to update item 2 and it works just fine:

https://little-esty-shop-project.herokuapp.com/merchants/1/items/2/edit

**Comment by alepbloyd** [comment]
@tig-o Oh awesome, thanks for testing that! I'll take a look at it now and do a PR once I figure out what the situation is.
